---
# Based on https://github.com/nicolas-van/rust-cross-compile-example - Thanks!

name: Publish

on:
  release:
    types:
      - published
  workflow_dispatch:
  pull_request: # for testing, when we change the workflow
    branches:
      - main
    paths:
      - .github/workflows/publish.yml

defaults:
  run:
    # necessary for windows
    shell: bash

jobs:
  chocolatey-publish:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - name: Testing
        run: |
          echo "1: $Env:GITHUB_REF_NAME"
          echo "2: ${{ github.ref_name }}"
          echo "3: ${{env.GITHUB_REF_NAME}}"
          echo "4: $GITHUB_REF_NAME"

          $version = $Env:GITHUB_REF_NAME -replace '^v', ''
          echo "$version"

          if ($version -notmatch '^\d+\.\d+\.\d+$') {
            $version = '9.9.9'
          }

          echo "$version"
